services:
    app:
        build:
            context: .
            target: php
            dockerfile: Dockerfile
        container_name: app-vehi-recu
        restart: unless-stopped
        tty: true
        working_dir: /var/www/
        volumes:
            - ./:/var/www/
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - vehi-recu-Net

    server:
        image: nginx:alpine
        container_name: server-vehi-recu
        restart: unless-stopped
        ports:
            - "801:80"
        volumes:
            - ./:/var/www/
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - vehi-recu-Net

networks:
    vehi-recu-Net:
        driver: bridge
