services:
    app:
        build:
            context: .
            target: php
            dockerfile: Dockerfile
        container_name: app-vehi-recu
        restart: unless-stopped
        tty: true
        working_dir: /var/www/
        volumes:
            - ./:/var/www/
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - vehi-recu-Net
        # depends_on:
        #     - db  # Añadimos una dependencia al servicio de base de datos

    server:
        image: nginx:alpine
        container_name: server-vehi-recu
        restart: unless-stopped
        ports:
            - "3020:80"
            - "443:443"
        volumes:
            - ./:/var/www/
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - vehi-recu-Net

#     db:
#         image: mysql:8.0
#         container_name: mysql-vehi-recu
#         restart: unless-stopped
#         ports:
#             - "3306:3306"
#         environment:
#             MYSQL_ROOT_PASSWORD: secret
#             MYSQL_DATABASE: vr
#             MYSQL_USER: vradmin
#             MYSQL_PASSWORD: vradmin
#         volumes:
#             - db_data:/var/lib/mysql
#         networks:
#             - vehi-recu-Net

# volumes:
#   db_data:

networks:
    vehi-recu-Net:
        driver: bridge
